// code written by binit
let data = JSON.parse(localStorage.getItem("score"));
let score = data || {
  win: 0,
  loss: 0,
  tie: 0,
};
let autoPlayId;
let isPlaying = false;
function autoPlay() {
  isPlaying = !isPlaying;
  if (isPlaying) {
    document.querySelector(".js-auto-play").innerHTML = "Stop";
    autoPlayId = setInterval(() => {
      const autoGeneratedMove = computerMove();
      myMove(autoGeneratedMove);
    }, [1000]);
  } else {
    document.querySelector(".js-auto-play").innerHTML = "Auto Play";
    clearInterval(autoPlayId);
    isPlaying = false;
  }
}

function resetScore() {
  score.win = 0;
  score.loss = 0;
  score.tie = 0;
  localStorage.removeItem("score");
  updateScore();
  window.location.reload();
}
function computerMove() {
  const moves = ["rock", "paper", "scissors"];
  const random = Math.floor(Math.random() * 3);
  return moves[random];
}

function updateScore() {
  let scoreElem = document.querySelector(".js-score");
  scoreElem.innerHTML = `Wins: ${score.win} Loss: ${score.loss} Tie: ${score.tie}`;
}
updateScore();
function showMove(yourMove, compMove) {
  document.querySelector(
    ".js-move"
  ).innerHTML = `You <img class="option-img" src="images/${yourMove}-emoji.png" /> Computer
      <img class="option-img" src="images/${compMove}-emoji.png" />`;
}
document.querySelector(".js-move");
function myMove(myChoice) {
  const computersChoice = computerMove();
  showMove(myChoice, computersChoice);
  let winner = "";
  if (myChoice === "rock" && computersChoice === "rock") {
    winner = "tie";
  } else if (myChoice === "rock" && computersChoice === "paper") {
    winner = "computer";
  } else if (myChoice === "rock" && computersChoice === "scissors") {
    winner = "human";
  }
  if (myChoice === "paper" && computersChoice === "rock") {
    winner = "human";
  } else if (myChoice === "paper" && computersChoice === "paper") {
    winner = "tie";
  } else if (myChoice === "paper" && computersChoice === "scissors") {
    winner = "computer";
  }
  if (myChoice === "scissors" && computersChoice === "rock") {
    winner = "computer";
  } else if (myChoice === "scissors" && computersChoice === "paper") {
    winner = "human";
  } else if (myChoice === "scissors" && computersChoice === "scissors") {
    winner = "tie";
  }
  if (winner === "human") {
    score.win = score.win + 1;
  } else if (winner === "computer") {
    score.loss = score.loss + 1;
  } else {
    score.tie = score.tie + 1;
  }
  if (winner === "human") {
    updateWinner("You Win.");
  } else if (winner === "computer") {
    updateWinner("You Lose.");
  } else {
    updateWinner("Tie.");
  }
  updateScore();
  localStorage.setItem("score", JSON.stringify(score));
}

function updateWinner(text) {
  document.querySelector(".js-winner").innerHTML = text;
}
